name: terraform

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: terraform apply

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
