name: terraform

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    name: terraform apply

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest Azure CLI
        run: curl -skL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true

